// Copyright (c) coherence ApS.
// For all coherence generated code, the coherence SDK license terms apply. See the license file in the coherence Package root folder for more information.

// <auto-generated>
// Generated file. DO NOT EDIT!
// </auto-generated>
namespace Coherence.Generated
{
    using Coherence.ProtocolDef;
    using Coherence.Serializer;
    using Coherence.Brook;
    using Coherence.Entities;
    using Coherence.Log;
    using Coherence.Core;
    using System.Collections.Generic;
    using System.Runtime.InteropServices;
    using UnityEngine;

    public struct EntityRefsCommand : IEntityCommand
    {
        [StructLayout(LayoutKind.Explicit)]
        public struct Interop
        {
            [FieldOffset(0)]
            public Entity entityRef1;
            [FieldOffset(4)]
            public Entity entityRef2;
        }

        public static unsafe EntityRefsCommand FromInterop(System.IntPtr data, System.Int32 dataSize) 
        {
            if (dataSize != 8) {
                throw new System.Exception($"Given data size is not equal to the struct size. ({dataSize} != 8) " +
                    "for command with ID 9");
            }

            var orig = new EntityRefsCommand();
            var comp = (Interop*)data;
            orig.entityRef1 = comp->entityRef1;
            orig.entityRef2 = comp->entityRef2;
            return orig;
        }

        public Entity entityRef1;
        public Entity entityRef2;
        
        public Entity Entity { get; set; }
        public Coherence.ChannelID ChannelID { get; set; }
        public MessageTarget Routing { get; set; }
        public uint Sender { get; set; }
        public uint GetComponentType() => 9;
        
        public IEntityMessage Clone()
        {
            // This is a struct, so we can safely return
            // a struct copy.
            return this;
        }
        
        public IEntityMapper.Error MapToAbsolute(IEntityMapper mapper, Coherence.Log.Logger logger)
        {
            var err = mapper.MapToAbsoluteEntity(Entity, false, out var absoluteEntity);
            if (err != IEntityMapper.Error.None)
            {
                return err;
            }
            Entity = absoluteEntity;
            err = mapper.MapToAbsoluteEntity(entityRef1, false, out absoluteEntity);
            if (err != IEntityMapper.Error.None)
            {
                return err;
            }
            this.entityRef1 = absoluteEntity;
            
            err = mapper.MapToAbsoluteEntity(entityRef2, false, out absoluteEntity);
            if (err != IEntityMapper.Error.None)
            {
                return err;
            }
            this.entityRef2 = absoluteEntity;
            
            return IEntityMapper.Error.None;
        }
        
        public IEntityMapper.Error MapToRelative(IEntityMapper mapper, Coherence.Log.Logger logger)
        {
            var err = mapper.MapToRelativeEntity(Entity, false, out var relativeEntity);
            if (err != IEntityMapper.Error.None)
            {
                return err;
            }
            Entity = relativeEntity;
            err = mapper.MapToRelativeEntity(entityRef1, false, out relativeEntity);
            if (err != IEntityMapper.Error.None)
            {
                return err;
            }
            this.entityRef1 = relativeEntity;
            
            err = mapper.MapToRelativeEntity(entityRef2, false, out relativeEntity);
            if (err != IEntityMapper.Error.None)
            {
                return err;
            }
            this.entityRef2 = relativeEntity;
            
            return IEntityMapper.Error.None;
        }

        public HashSet<Entity> GetEntityRefs() {
            return new HashSet<Entity> {
                this.entityRef1,
                this.entityRef2,
            };
        }

        public void NullEntityRefs(Entity entity) {
            if (this.entityRef1 == entity) {
                this.entityRef1 = Entity.InvalidRelative;
            }
            if (this.entityRef2 == entity) {
                this.entityRef2 = Entity.InvalidRelative;
            }
        }
        
        public EntityRefsCommand(
        Entity entity,
        Entity entityRef1,
        Entity entityRef2
)
        {
            Entity = entity;
            ChannelID = Coherence.ChannelID.Default;
            Routing = MessageTarget.All;
            Sender = 0;
            
            this.entityRef1 = entityRef1; 
            this.entityRef2 = entityRef2; 
        }
        
        public static void Serialize(EntityRefsCommand commandData, IOutProtocolBitStream bitStream)
        {
            bitStream.WriteEntity(commandData.entityRef1);
            bitStream.WriteEntity(commandData.entityRef2);
        }
        
        public static EntityRefsCommand Deserialize(IInProtocolBitStream bitStream, Entity entity, MessageTarget target)
        {
            var dataentityRef1 = bitStream.ReadEntity();
            var dataentityRef2 = bitStream.ReadEntity();
    
            return new EntityRefsCommand()
            {
                Entity = entity,
                Routing = target,
                entityRef1 = dataentityRef1,
                entityRef2 = dataentityRef2
            };   
        }
    }

}
