// Copyright (c) coherence ApS.
// For all coherence generated code, the coherence SDK license terms apply. See the license file in the coherence Package root folder for more information.

// <auto-generated>
// Generated file. DO NOT EDIT!
// </auto-generated>
namespace Coherence.Generated
{
    using Coherence.ProtocolDef;
    using Coherence.Serializer;
    using Coherence.Brook;
    using Coherence.Entities;
    using Coherence.Log;
    using Coherence.Core;
    using System.Collections.Generic;
    using System.Runtime.InteropServices;
    using System;
    using UnityEngine;

    public struct FloatInput : IEntityInput, IEquatable<FloatInput>
    {
        [StructLayout(LayoutKind.Explicit)]
        public struct Interop
        {
            [FieldOffset(0)]
            public System.Single floatField;
        }

        public static unsafe FloatInput FromInterop(System.IntPtr data, System.Int32 dataSize)
        {
            if (dataSize != 4) {
                throw new System.Exception($"Given data size is not equal to the struct size. ({dataSize} != 4) " +
                    "for input with ID 2");
            }

            var orig = new FloatInput();
            var comp = (Interop*)data;
            orig.floatField = comp->floatField;
            return orig;
        }

        public uint GetComponentType() => 2;

        public Entity Entity { get; set; }
        public Coherence.ChannelID ChannelID { get; set; }
        public MessageTarget Routing { get; set; }
        public uint Sender { get; set; }
        public long Frame { get; set; }
        private bool isRemoteInput;

        public System.Single floatField;

        public FloatInput(
        Entity entity,
        long frame,
        System.Single floatField,
        bool isRemoteInput)
        {
            this.Entity = entity;
            this.ChannelID = Coherence.ChannelID.Default;
            this.Routing = MessageTarget.All;
            this.Sender = 0;
            this.Frame = frame;
            this.isRemoteInput = isRemoteInput;
            this.floatField = floatField;
        }

        public override string ToString()
        {
            return $"Entity: {Entity}, Frame: {Frame}, Inputs: [floatField:{floatField}]";
        }

        public IEntityMessage Clone()
        {
            // This is a struct, so we can safely return
            // a struct copy.
            return this;
        }

        public IEntityMapper.Error MapToAbsolute(IEntityMapper mapper, Coherence.Log.Logger logger)
        {
            var err = mapper.MapToAbsoluteEntity(Entity, false, out var absoluteEntity);
            if (err != IEntityMapper.Error.None)
            {
                return err;
            }
            Entity = absoluteEntity;
            return IEntityMapper.Error.None;
        }

        public IEntityMapper.Error MapToRelative(IEntityMapper mapper, Coherence.Log.Logger logger)
        {
            var err = mapper.MapToRelativeEntity(Entity, false, out var relativeEntity);
            if (err != IEntityMapper.Error.None)
            {
                return err;
            }
            Entity = relativeEntity;
            return IEntityMapper.Error.None;
        }

        public HashSet<Entity> GetEntityRefs() => default;

        public void NullEntityRefs(Entity entity) { }

        public bool Equals(FloatInput other)
        {
            return
                this.floatField == other.floatField;
        }

        public static void Serialize(FloatInput inputData, IOutProtocolBitStream bitStream)
        {
            bitStream.WriteFloat(inputData.floatField, FloatMeta.NoCompression());
        }

        public static FloatInput Deserialize(IInProtocolBitStream bitStream, Entity entity, long frame)
        {
            var datafloatField = bitStream.ReadFloat(FloatMeta.NoCompression());

            return new FloatInput()
            {
                Entity = entity,
                Frame = frame,
                floatField = datafloatField,
                isRemoteInput = true
            };
        }
    }

}
