// Copyright (c) coherence ApS.
// For all coherence generated code, the coherence SDK license terms apply. See the license file in the coherence Package root folder for more information.

// <auto-generated>
// Generated file. DO NOT EDIT!
// </auto-generated>
namespace Coherence.Generated
{
    using System;
    using System.Runtime.InteropServices;
    using System.Collections.Generic;
    using Coherence.ProtocolDef;
    using Coherence.Serializer;
    using Coherence.SimulationFrame;
    using Coherence.Entities;
    using Coherence.Utils;
    using Coherence.Brook;
    using Coherence.Core;
    using Logger = Coherence.Log.Logger;
    using UnityEngine;
    using Coherence.Toolkit;
    public struct SimFramesComponent : ICoherenceComponentData
    {
        [StructLayout(LayoutKind.Explicit)]
        public struct Interop
        {
            [FieldOffset(0)]
            public System.Int32 simFrameIntValue;
            [FieldOffset(4)]
            public System.Single floatValue;
            [FieldOffset(8)]
            public System.Single simFrameFloatValue;
        }

        public void ResetFrame(AbsoluteSimulationFrame frame)
        {
            FieldsMask |= SimFramesComponent.simFrameIntValueMask;
            simFrameIntValueSimulationFrame = frame;
            FieldsMask |= SimFramesComponent.floatValueMask;
            floatValueSimulationFrame = frame;
            FieldsMask |= SimFramesComponent.simFrameFloatValueMask;
            simFrameFloatValueSimulationFrame = frame;
        }

        public static unsafe SimFramesComponent FromInterop(IntPtr data, Int32 dataSize, InteropAbsoluteSimulationFrame* simFrames, Int32 simFramesCount)
        {
            if (dataSize != 12) {
                throw new Exception($"Given data size is not equal to the struct size. ({dataSize} != 12) " +
                    "for component with ID 22");
            }

            if (simFramesCount != 2) {
                throw new Exception($"Given simFrames size is not equal to the expected length. ({simFramesCount} != 2) " +
                    "for component with ID 22");
            }

            var orig = new SimFramesComponent();

            var comp = (Interop*)data;

            orig.simFrameIntValue = comp->simFrameIntValue;
            orig.simFrameIntValueSimulationFrame = simFrames[0].Into();
            orig.floatValue = comp->floatValue;
            orig.simFrameFloatValue = comp->simFrameFloatValue;
            orig.simFrameFloatValueSimulationFrame = simFrames[1].Into();

            return orig;
        }


        public static uint simFrameIntValueMask => 0b00000000000000000000000000000001;
        public AbsoluteSimulationFrame simFrameIntValueSimulationFrame;
        public System.Int32 simFrameIntValue;
        public static uint floatValueMask => 0b00000000000000000000000000000010;
        public AbsoluteSimulationFrame floatValueSimulationFrame;
        public System.Single floatValue;
        public static uint simFrameFloatValueMask => 0b00000000000000000000000000000100;
        public AbsoluteSimulationFrame simFrameFloatValueSimulationFrame;
        public System.Single simFrameFloatValue;

        public uint FieldsMask { get; set; }
        public uint StoppedMask { get; set; }
        public uint GetComponentType() => 22;
        public int PriorityLevel() => 100;
        public const int order = 0;
        public uint InitialFieldsMask() => 0b00000000000000000000000000000111;
        public bool HasFields() => true;
        public bool HasRefFields() => false;

        private long[] simulationFrames;

        public long[] GetSimulationFrames() {
            if (simulationFrames == null)
            {
                simulationFrames = new long[2];
            }

            simulationFrames[0] = simFrameIntValueSimulationFrame;
            simulationFrames[1] = simFrameFloatValueSimulationFrame;

            return simulationFrames;
        }

        public int GetFieldCount() => 3;


        
        public HashSet<Entity> GetEntityRefs()
        {
            return default;
        }

        public uint ReplaceReferences(Entity fromEntity, Entity toEntity)
        {
            return 0;
        }
        
        public IEntityMapper.Error MapToAbsolute(IEntityMapper mapper)
        {
            return IEntityMapper.Error.None;
        }

        public IEntityMapper.Error MapToRelative(IEntityMapper mapper)
        {
            return IEntityMapper.Error.None;
        }

        public ICoherenceComponentData Clone() => this;
        public int GetComponentOrder() => order;
        public bool IsSendOrdered() => false;


        public AbsoluteSimulationFrame? GetMinSimulationFrame()
        {
            AbsoluteSimulationFrame? min = null;

            if ((FieldsMask & SimFramesComponent.simFrameIntValueMask) != 0 && (min == null || this.simFrameIntValueSimulationFrame < min))
            {
                min = this.simFrameIntValueSimulationFrame;
            }
            if ((FieldsMask & SimFramesComponent.simFrameFloatValueMask) != 0 && (min == null || this.simFrameFloatValueSimulationFrame < min))
            {
                min = this.simFrameFloatValueSimulationFrame;
            }

            return min;
        }

        public ICoherenceComponentData MergeWith(ICoherenceComponentData data)
        {
            var other = (SimFramesComponent)data;
            var otherMask = other.FieldsMask;

            FieldsMask |= otherMask;
            StoppedMask &= ~(otherMask);

            if ((otherMask & 0x01) != 0)
            {
                this.simFrameIntValueSimulationFrame = other.simFrameIntValueSimulationFrame;
                this.simFrameIntValue = other.simFrameIntValue;
            }

            otherMask >>= 1;
            if ((otherMask & 0x01) != 0)
            {
                this.floatValueSimulationFrame = other.floatValueSimulationFrame;
                this.floatValue = other.floatValue;
            }

            otherMask >>= 1;
            if ((otherMask & 0x01) != 0)
            {
                this.simFrameFloatValueSimulationFrame = other.simFrameFloatValueSimulationFrame;
                this.simFrameFloatValue = other.simFrameFloatValue;
            }

            otherMask >>= 1;
            StoppedMask |= other.StoppedMask;

            return this;
        }

        public uint DiffWith(ICoherenceComponentData data)
        {
            throw new System.NotSupportedException($"{nameof(DiffWith)} is not supported in Unity");
        }

        public static uint Serialize(SimFramesComponent data, bool isRefSimFrameValid, AbsoluteSimulationFrame referenceSimulationFrame, IOutProtocolBitStream bitStream, Logger logger)
        {
            if (bitStream.WriteMask(data.StoppedMask != 0))
            {
                bitStream.WriteMaskBits(data.StoppedMask, 3);
            }

            var mask = data.FieldsMask;

            if (bitStream.WriteMask((mask & 0x01) != 0))
            {
                if (isRefSimFrameValid) {
                    var simFrameDelta = data.simFrameIntValueSimulationFrame - referenceSimulationFrame;
                    if (simFrameDelta > byte.MaxValue) {
                        simFrameDelta = byte.MaxValue;
                    }

                    SerializeTools.WriteFieldSimFrameDelta(bitStream, (byte)simFrameDelta);
                } else {
                    SerializeTools.WriteFieldSimFrameDelta(bitStream, 0);
                }


                var fieldValue = data.simFrameIntValue;



                bitStream.WriteIntegerRange(fieldValue, 32, -2147483648);
            }

            mask >>= 1;
            if (bitStream.WriteMask((mask & 0x01) != 0))
            {


                var fieldValue = data.floatValue;



                bitStream.WriteFloat(fieldValue, FloatMeta.NoCompression());
            }

            mask >>= 1;
            if (bitStream.WriteMask((mask & 0x01) != 0))
            {
                if (isRefSimFrameValid) {
                    var simFrameDelta = data.simFrameFloatValueSimulationFrame - referenceSimulationFrame;
                    if (simFrameDelta > byte.MaxValue) {
                        simFrameDelta = byte.MaxValue;
                    }

                    SerializeTools.WriteFieldSimFrameDelta(bitStream, (byte)simFrameDelta);
                } else {
                    SerializeTools.WriteFieldSimFrameDelta(bitStream, 0);
                }


                var fieldValue = data.simFrameFloatValue;



                bitStream.WriteFloat(fieldValue, FloatMeta.NoCompression());
            }

            mask >>= 1;

            return mask;
        }

        public static SimFramesComponent Deserialize(AbsoluteSimulationFrame referenceSimulationFrame, InProtocolBitStream bitStream)
        {
            var stoppedMask = (uint)0;
            if (bitStream.ReadMask())
            {
                stoppedMask = bitStream.ReadMaskBits(3);
            }

            var val = new SimFramesComponent();
            if (bitStream.ReadMask())
            {
                val.simFrameIntValueSimulationFrame = referenceSimulationFrame + DeserializerTools.ReadFieldSimFrameDelta(bitStream);

                val.simFrameIntValue = bitStream.ReadIntegerRange(32, -2147483648);
                val.FieldsMask |= SimFramesComponent.simFrameIntValueMask;
            }
            if (bitStream.ReadMask())
            {

                val.floatValue = bitStream.ReadFloat(FloatMeta.NoCompression());
                val.FieldsMask |= SimFramesComponent.floatValueMask;
            }
            if (bitStream.ReadMask())
            {
                val.simFrameFloatValueSimulationFrame = referenceSimulationFrame + DeserializerTools.ReadFieldSimFrameDelta(bitStream);

                val.simFrameFloatValue = bitStream.ReadFloat(FloatMeta.NoCompression());
                val.FieldsMask |= SimFramesComponent.simFrameFloatValueMask;
            }

            val.StoppedMask = stoppedMask;

            return val;
        }


        public override string ToString()
        {
            return $"SimFramesComponent(" +
                $" simFrameIntValue: { this.simFrameIntValue }" +
                $", simFrameIntValueSimFrame: { this.simFrameIntValueSimulationFrame }" +
                $" floatValue: { this.floatValue }" +
                $" simFrameFloatValue: { this.simFrameFloatValue }" +
                $", simFrameFloatValueSimFrame: { this.simFrameFloatValueSimulationFrame }" +
                $" Mask: { System.Convert.ToString(FieldsMask, 2).PadLeft(3, '0') }, " +
                $"Stopped: { System.Convert.ToString(StoppedMask, 2).PadLeft(3, '0') })";
        }
    }

}
