// Copyright (c) coherence ApS.
// For all coherence generated code, the coherence SDK license terms apply. See the license file in the coherence Package root folder for more information.

// <auto-generated>
// Generated file. DO NOT EDIT!
// </auto-generated>
namespace Coherence.Generated
{
    using Coherence.ProtocolDef;
    using Coherence.Serializer;
    using Coherence.Brook;
    using Coherence.Entities;
    using Coherence.Log;
    using Coherence.Core;
    using System.Collections.Generic;
    using System.Runtime.InteropServices;
    using System;
    using UnityEngine;

    public struct StringInput : IEntityInput, IEquatable<StringInput>
    {
        [StructLayout(LayoutKind.Explicit)]
        public struct Interop
        {
            [FieldOffset(0)]
            public ByteArray stringField;
        }

        public static unsafe StringInput FromInterop(System.IntPtr data, System.Int32 dataSize)
        {
            if (dataSize != 16) {
                throw new System.Exception($"Given data size is not equal to the struct size. ({dataSize} != 16) " +
                    "for input with ID 6");
            }

            var orig = new StringInput();
            var comp = (Interop*)data;
            orig.stringField = comp->stringField.Data != null ? System.Text.Encoding.UTF8.GetString((byte*)comp->stringField.Data, (int)comp->stringField.Length) : null;
            return orig;
        }

        public uint GetComponentType() => 6;

        public Entity Entity { get; set; }
        public Coherence.ChannelID ChannelID { get; set; }
        public MessageTarget Routing { get; set; }
        public uint Sender { get; set; }
        public long Frame { get; set; }
        private bool isRemoteInput;

        public System.String stringField;

        public StringInput(
        Entity entity,
        long frame,
        System.String stringField,
        bool isRemoteInput)
        {
            this.Entity = entity;
            this.ChannelID = Coherence.ChannelID.Default;
            this.Routing = MessageTarget.All;
            this.Sender = 0;
            this.Frame = frame;
            this.isRemoteInput = isRemoteInput;
            this.stringField = stringField;
        }

        public override string ToString()
        {
            return $"Entity: {Entity}, Frame: {Frame}, Inputs: [stringField:{stringField}]";
        }

        public IEntityMessage Clone()
        {
            // This is a struct, so we can safely return
            // a struct copy.
            return this;
        }

        public IEntityMapper.Error MapToAbsolute(IEntityMapper mapper, Coherence.Log.Logger logger)
        {
            var err = mapper.MapToAbsoluteEntity(Entity, false, out var absoluteEntity);
            if (err != IEntityMapper.Error.None)
            {
                return err;
            }
            Entity = absoluteEntity;
            return IEntityMapper.Error.None;
        }

        public IEntityMapper.Error MapToRelative(IEntityMapper mapper, Coherence.Log.Logger logger)
        {
            var err = mapper.MapToRelativeEntity(Entity, false, out var relativeEntity);
            if (err != IEntityMapper.Error.None)
            {
                return err;
            }
            Entity = relativeEntity;
            return IEntityMapper.Error.None;
        }

        public HashSet<Entity> GetEntityRefs() => default;

        public void NullEntityRefs(Entity entity) { }

        public bool Equals(StringInput other)
        {
            return
                this.stringField == other.stringField;
        }

        public static void Serialize(StringInput inputData, IOutProtocolBitStream bitStream)
        {
            bitStream.WriteShortString(inputData.stringField);
        }

        public static StringInput Deserialize(IInProtocolBitStream bitStream, Entity entity, long frame)
        {
            var datastringField = bitStream.ReadShortString();

            return new StringInput()
            {
                Entity = entity,
                Frame = frame,
                stringField = datastringField,
                isRemoteInput = true
            };
        }
    }

}
